language: go
go:
  - 1.18.x
node_js: "12.16.3"
git:
  depth: 1
before_install:
  - mkdir assets/build
  - touch assets/build/test.html
script:
  - go test -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - sudo apt-get update
  - sudo apt-get -y install gcc-mingw-w64-x86-64
  - sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
  - sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
  - chmod +x ./build.sh
  - ./build.sh -r b
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: release/*
  draft: true
  skip_cleanup: true
  on:
    tags: true
